
port : 8000

mongo:
  host : 'perterpon.wicp.net'
  user : 'note'
  password : 'hello1234'
  db   : 'note'

# mongo:
#   host : '127.0.0.1'
#   user : 'note'
#   password : 'hello1234'
#   db   : 'note'
